### PR TITLE
Fix Failure writing output to destination in curl

### PR DESCRIPTION
**Pull request by mohamad-supangat**

### CODE REVIEW

**Review by Atrate — APPROVED** [review]
LGTM

**Comment by tytydraco** [comment]
Are we sure that most curl implementations on Android have this flag? Is this a universal change?

**Comment by Atrate** [comment]
From a cursory research, `--create-dirs` has been in `curl` for over 10 years, I think it's safe to assume most, if not all, Android phones will have that. Could be checked on some really old devices.

**Comment by tytydraco** [comment]
> From a cursory research, `--create-dirs` has been in `curl` for over 10 years, I think it's safe to assume most, if not all, Android phones will have that. Could be checked on some really old devices.

Probably right. Let's hope.. ;)

**Comment by mohamad-supangat** [comment]
I'm sorry just got online again, and forgot to include a description :')

device : samsung s7 edge
android version : 8.0 stock touchwizard
magisk : 23.0

and now it's working perfectly

thank you

**Pull request merged**
